In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [2]:
df = pd.read_csv('smsspam.txt', sep='\t', names=['Status', 'Message'])

In [3]:
df.head()

  Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
len(df)

5572

In [5]:
len(df[df.Status=='spam'])

747

In [6]:
df.loc[df["Status"]=='ham', "Status"]=1
df.loc[df["Status"]=='spam', "Status"]=0

In [7]:
df.head()

  Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [8]:
df_x=df["Message"]
df_y=df["Status"]

In [9]:
df_x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will Ã¼ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [10]:
cv=CountVectorizer()

In [11]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [12]:
x_traincv=cv.fit_transform(x_train)

In [13]:
a=x_traincv.toarray()

In [14]:
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
cv.inverse_transform(a[[0]])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'me', 'now',
        'online', 'or', 'replying', 'sleeping', 'spys', 'take', 'to',
        'wat', 'you'], dtype='<U27')]

In [17]:
x_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

In [24]:
cv.vocabulary_

{'sleeping': 6225,
 'now': 4852,
 'or': 4990,
 'you': 7719,
 'going': 3174,
 'to': 6944,
 'take': 6700,
 'haha': 3296,
 'got': 3200,
 'spys': 6429,
 'wat': 7413,
 'me': 4415,
 'online': 4958,
 'checking': 1766,
 'replying': 5720,
 'mails': 4327,
 'lor': 4212,
 'how': 3515,
 'long': 4197,
 'has': 3342,
 'it': 3752,
 'been': 1297,
 'since': 6178,
 'screamed': 5963,
 'princess': 5426,
 'urgent': 7220,
 'call': 1612,
 '09066612661': 233,
 'from': 3023,
 'landline': 4004,
 'your': 7725,
 'complementary': 1935,
 'tenerife': 6780,
 'holiday': 3462,
 '10': 252,
 '000': 1,
 'cash': 1682,
 'await': 1173,
 'collection': 1901,
 'sae': 5876,
 'cs': 2098,
 'po': 5278,
 'box': 1462,
 'wa14': 7360,
 '2px': 413,
 '150ppm': 305,
 '18': 318,
 'sender': 6017,
 'hol': 3457,
 'offer': 4911,
 'okay': 4931,
 'no': 4806,
 'just': 3871,
 'shining': 6095,
 'on': 4948,
 'that': 6825,
 'was': 7407,
 'meant': 4423,
 'be': 1276,
 'signing': 6166,
 'but': 1580,
 'sounds': 6351,
 'better': 1336,
 'wen': 7472,
 'ur': 7216,
 'lovable': 4233,
 'bcums': 1273,
 'angry': 971,
 'wid': 7522,
 'dnt': 2383,
 'seriously': 6036,
 'coz': 2051,
 'being': 1315,
 'is': 3742,
 'most': 4599,
 'childish': 1792,
 'true': 7060,
 'way': 7428,
 'of': 4905,
 'showing': 6137,
 'deep': 2221,
 'affection': 853,
 'care': 1661,
 'luv': 4272,
 'kettoda': 3917,
 'manda': 4347,
 'have': 3356,
 'nice': 4784,
 'day': 2189,
 'da': 2151,
 'we': 7432,
 'll': 4163,
 'do': 2384,
 'medical': 4430,
 'missions': 4519,
 'nigeria': 4788,
 'dunno': 2493,
 'juz': 3877,
 'askin': 1102,
 'cos': 2025,
 'card': 1657,
 '20': 346,
 'off': 4907,
 'salon': 5891,
 'called': 1619,
 'hair': 3299,
 'sense': 6022,
 'so': 6289,
 'tot': 7005,
 'one': 4954,
 'cut': 2139,
 'win': 7535,
 'year': 7693,
 'supply': 6625,
 'cds': 1706,
 'store': 6515,
 'choice': 1809,
 'worth': 7619,
 '500': 537,
 'enter': 2612,
 'our': 5021,
 '100': 253,
 'weekly': 7457,
 'draw': 2448,
 'txt': 7105,
 'music': 4664,
 '87066': 694,
 'ts': 7071,
 'www': 7653,
 'ldew': 4049,
 'com': 1906,
 'subs16': 6568,
 '1win150ppmx3': 341,
 'fetch': 2821,
 'yun': 7740,
 'sent': 6026,
 'an': 961,
 'email': 2576,
 'address': 825,
 'with': 7561,
 'incomm': 3646,
 'in': 3635,
 'right': 5786,
 'yep': 7701,
 'then': 6839,
 'fine': 2859,
 '30': 425,
 'for': 2941,
 'ice': 3576,
 'age': 870,
 'dont': 2419,
 'know': 3958,
 'exactly': 2693,
 'could': 2033,
 'ask': 1099,
 'chechi': 1761,
 'guess': 3269,
 'useless': 7237,
 'calling': 1625,
 'something': 6313,
 'important': 3624,
 'poyyarikatur': 5366,
 'kolathupalayam': 3965,
 'unjalur': 7179,
 'post': 5346,
 'erode': 2636,
 'dis': 2347,
 'lt': 4255,
 'gt': 3259,
 'sos': 6347,
 'any': 999,
 'amount': 953,
 'can': 1636,
 'get': 3121,
 'pls': 5271,
 'what': 7489,
 'time': 6915,
 'out': 5024,
 'until': 7197,
 'prob': 5436,
 'the': 6828,
 'bus': 1573,
 'yes': 7703,
 'please': 5263,
 'swimming': 6670,
 'as': 1092,
 'missionary': 4518,
 'hook': 3480,
 'up': 7199,
 'doggy': 2405,
 'standing': 6451,
 'si': 6152,
 'como': 1925,
 'listened2the': 4145,
 'plaid': 5247,
 'album': 905,
 'quite': 5540,
 'gd': 3100,
 'new': 4771,
 'air1': 891,
 'which': 7505,
 'hilarious': 3424,
 'also': 930,
 'bought': 1456,
 'braindance': 1486,
 'comp': 1926,
 'ofstuff': 4922,
 'aphex': 1018,
 'abel': 759,
 'hav2hear': 3353,
 'sn': 6274,
 'xxxx': 7672,
 'wot': 7620,
 'wanna': 7392,
 'missy': 4522,
 'free': 2987,
 'ring': 5791,
 'tone': 6973,
 'text': 6800,
 'polys': 5314,
 '87131': 698,
 'every': 2671,
 'week': 7453,
 '0870737910216yrs': 80,
 'only': 4960,
 '50': 536,
 'wk': 7567,
 'alright': 928,
 'see': 5989,
 'bit': 1372,
 'ugh': 7127,
 'its': 3760,
 'exhausted': 2708,
 'want': 7394,
 'cuddle': 2114,
 'and': 965,
 'nap': 4705,
 'yo': 7714,
 'guys': 3283,
 'ever': 2670,
 'figure': 2840,
 'much': 4641,
 'need': 4736,
 'alcohol': 906,
 'jay': 3795,
 'are': 1056,
 'trying': 7070,
 'safely': 5879,
 'spend': 6389,
 'weed': 7452,
 'when': 7495,
 'don': 2415,
 'my': 4675,
 'phones': 5206,
 'having': 3362,
 'problems': 5439,
 'miss': 4513,
 'vday': 7273,
 'parachute': 5089,
 'double': 2432,
 'coins': 1890,
 'must': 4667,
 'not': 4840,
 'very': 7287,
 'well': 7469,
 'super': 6619,
 'msg': 4624,
 'nalla': 4693,
 'timing': 6919,
 'hurting': 3557,
 'meaningful': 4420,
 'lines': 4130,
 'compromised': 1945,
 'everything': 2680,
 'love': 4234,
 'at': 1122,
 'end': 2589,
 'gud': 3265,
 'mornin': 4593,
 'he': 3367,
 'dint': 2338,
 'tell': 6766,
 'anything': 1007,
 'why': 7517,
 'told': 6960,
 'abi': 761,
 've': 7274,
 'already': 927,
 'flaky': 2886,
 'parent': 5097,
 'snot': 6283,
 'supposed': 6629,
 'child': 1791,
 'job': 3826,
 'support': 6626,
 'they': 6850,
 're': 5593,
 'ride': 5785,
 'anyway': 1010,
 'there': 6843,
 'hurt': 3556,
 'unintentional': 7172,
 'nonetheless': 4822,
 'sorry': 6339,
 'im': 3610,
 'stil': 6496,
 'fucked': 3032,
 'after': 862,
 'last': 4022,
 'nite': 4800,
 'went': 7474,
 'tobed': 6948,
 '430': 490,
 'work': 7603,
 '630': 582,
 'dear': 2201,
 'friends': 3009,
 'late': 4025,
 'information': 3670,
 'today': 6951,
 'birthday': 1370,
 'loving': 4244,
 'ar': 1051,
 'praveesh': 5384,
 'more': 4590,
 'details': 2284,
 'log': 4182,
 'face': 2743,
 'book': 1432,
 'his': 3435,
 'number': 4867,
 'delicious': 2241,
 'treat': 7044,
 'restrict': 5756,
 'her': 3408,
 'eating': 2524,
 'anythin': 1006,
 'she': 6081,
 'likes': 4117,
 'next': 4780,
 'two': 7103,
 'days': 2190,
 'life': 4104,
 'choices': 1810,
 'toss': 7004,
 'coin': 1888,
 'becoz': 1290,
 'settle': 6044,
 'question': 5533,
 'while': 7506,
 'air': 890,
 'will': 7532,
 'heart': 3381,
 'hoping': 3492,
 'gudni8': 3266,
 'goodmorning': 3187,
 'am': 938,
 'decimal': 2212,
 'min': 4491,
 'never': 4767,
 'invite': 3721,
 'anywhere': 1012,
 'sure': 6633,
 'make': 4331,
 'knows': 3961,
 'ain': 888,
 'smokin': 6266,
 'yet': 7706,
 'free2day': 2988,
 'sexy': 6053,
 'st': 6438,
 'george': 3117,
 'pic': 5215,
 'jordan': 3845,
 '89080': 715,
 'saucy': 5925,
 'celeb': 1708,
 'pics': 5220,
 'pocketbabe': 5295,
 'co': 1878,
 'uk': 7133,
 '0870241182716': 74,
 'say': 5932,
 'cant': 1647,
 'wait': 7371,
 'again': 868,
 'getting': 3128,
 'bored': 1444,
 'this': 6866,
 'bridgwater': 1508,
 'banter': 1231,
 'looking': 4205,
 'like': 4114,
 'italian': 3753,
 'food': 2931,
 'where': 7499,
 'dollars': 2412,
 'hi': 3419,
 'balance': 1218,
 '600': 572,
 'complete': 1936,
 'landmark': 4007,
 'big': 1352,
 'bob': 1420,
 'barry': 1241,
 'ben': 1325,
 '83738': 675,
 'good': 3184,
 'luck': 4260,
 'paragon': 5091,
 'noe': 4810,
 'hey': 3416,
 'gals': 3068,
 'anyone': 1002,
 'down': 2436,
 'driving': 2465,
 'centre': 1716,
 'tmr': 6939,
 'man': 4341,
 'account': 795,
 'dry': 2480,
 'would': 7624,
 'if': 3592,
 'trade': 7020,
 'back': 1203,
 'half': 3304,
 'buy': 1585,
 'some': 6304,
 'shit': 6102,
 'credit': 2074,
 'won': 7588,
 'guaranteed': 3263,
 '200': 347,
 'award': 1176,
 'even': 2665,
 '1000': 254,
 'cashto': 1685,
 'claim': 1831,
 '08000407165': 47,
 'stop': 6507,
 'getstop': 3126,
 '88222': 707,
 'php': 5210,
 'rg21': 5777,
 '4jx': 522,
 'wan2': 7390,
 'meet': 4434,
 'greet': 3242,
 'westlife': 7484,
 'm8': 4289,
 'currently': 2128,
 'tour': 7013,
 'unbreakable': 7144,
 'untamed': 7196,
 'unkempt': 7180,
 '83049': 666,
 'cost': 2026,
 '50p': 543,
 'std': 6477,
 'oops': 4970,
 'let': 4089,
 'roommate': 5822,
 'done': 2417,
 'oic': 4927,
 'sis': 6192,
 'lunch': 4267,
 'dad': 2155,
 'whether': 7504,
 'eat': 2521,
 'sch': 5944,
 'did': 2309,
 'message': 4465,
 'plz': 5275,
 'note': 4841,
 'mobile': 4547,
 'amp': 954,
 'asks': 1104,
 'type': 7119,
 'disconnect': 2356,
 'iz': 3770,
 'attempt': 1133,
 'terrorist': 6791,
 'use': 7234,
 'sim': 6173,
 'itz': 3764,
 'confirmd': 1963,
 'by': 1595,
 'nokia': 4816,
 'motorola': 4607,
 'verified': 7282,
 'cnn': 1876,
 'ibn': 3572,
 'rightio': 5787,
 '11': 267,
 '48': 508,
 'arent': 1059,
 'all': 918,
 'bright': 1510,
 'early': 2511,
 'morning': 4594,
 'maybe': 4408,
 'find': 2858,
 'great': 3236,
 'escape': 2646,
 'wetherspoons': 7486,
 'first': 2874,
 'dhoni': 2298,
 'rocks': 5810,
 'xy': 7678,
 'shows': 6140,
 'coveragd': 2049,
 'area': 1057,
 'urgnt': 7223,
 'vasai': 7269,
 'reach': 5594,
 'before': 1303,
 'clock': 1854,
 'search': 5974,
 'happiness': 3333,
 'main': 4328,
 'sources': 6355,
 'unhappiness': 7167,
 'accept': 785,
 'comes': 1913,
 'moment': 4569,
 'live': 4155,
 'ok': 4930,
 'thats': 6827,
 'cool': 2010,
 'either': 2558,
 'raglan': 5553,
 'rd': 5592,
 'edward': 2539,
 'behind': 1313,
 'cricket': 2081,
 'ground': 3250,
 'gimme': 3139,
 'closeby': 1858,
 'tuesday': 7082,
 'oh': 4925,
 'ho': 3454,
 'these': 6845,
 'words': 7602,
 'takes': 6702,
 'part': 5105,
 'wrc': 7629,
 'rally': 5566,
 'oz': 5056,
 'lucozade': 4263,
 'energy': 2598,
 'le': 4052,
 '61200': 576,
 '25p': 372,
 'packs': 5062,
 'itcould': 3754,
 'ya': 7680,
 'awarded': 1177,
 'bonus': 1430,
 'caller': 1620,
 'prize': 5434,
 '08': 45,
 '03': 11,
 '2nd': 407,
 'contact': 1984,
 '0871': 88,
 '4719': 505,
 '523': 552,
 'box95qu': 1476,
 'bt': 1544,
 'national': 4714,
 'rate': 5578,
 'fuck': 3031,
 'juswoke': 3876,
 'bed': 1292,
 'boatin': 1419,
 'docks': 2389,
 'slept': 6230,
 '25': 368,
 'old': 4941,
 'spinout': 6398,
 'giv': 3146,
 'gossip': 3199,
 'l8r': 3981,
 'xxx': 7671,
 'hope': 3484,
 'endowed': 2594,
 'inches': 3639,
 'understand': 7156,
 '08712402779': 100,
 'immediately': 3620,
 'waiting': 7374,
 'yeah': 7692,
 'imagine': 3613,
 'really': 5611,
 'gentle': 3113,
 'unlike': 7183,
 'other': 5014,
 'docs': 2390,
 'who': 7511,
 'their': 6834,
 'patients': 5128,
 'turkeys': 7088,
 'short': 6120,
 'cute': 2140,
 'person': 5179,
 'try': 7068,
 'prove': 5476,
 'mrng': 4621,
 'dhanush': 2296,
 'once': 4952,
 'doc': 2387,
 'shirt': 6100,
 'hubby': 3532,
 'fiting': 2877,
 'ones': 4955,
 'budget': 1551,
 'help': 3401,
 'load': 4169,
 'hw': 3564,
 'keep': 3907,
 'posted': 5350,
 'mj': 4528,
 'hooked': 3481,
 'edison': 2532,
 'rightly': 5788,
 'said': 5883,
 'fool': 2932,
 'questions': 5535,
 'than': 6813,
 'wise': 7552,
 'answer': 988,
 'us': 7230,
 'speechless': 6381,
 'during': 2497,
 'viva': 7326,
 'gm': 3156,
 'gn': 3158,
 'ge': 3102,
 'gnt': 3160,
 'married': 4372,
 'local': 4174,
 'women': 7587,
 'discreet': 2359,
 'action': 810,
 'real': 5603,
 'matches': 4386,
 'instantly': 3695,
 'phone': 5202,
 'match': 4385,
 '69969': 601,
 '150p': 301,
 'bcmsfwc1n3xx': 1269,
 'aathi': 754,
 'video': 7297,
 'tape': 6721,
 'pple': 5368,
 'wan': 7389,
 'hee': 3389,
 'watch': 7414,
 'infernal': 3666,
 'affairs': 852,
 'along': 926,
 'asking': 1103,
 'shuhui': 6148,
 'oso': 5012,
 'eh': 2553,
 'laptop': 4014,
 'stock': 6499,
 'lei': 4077,
 'mon': 4572,
 'muz': 4672,
 'come': 1911,
 'look': 4201,
 'salt': 5892,
 'rub': 5845,
 'open': 4971,
 'wounds': 7627,
 'chic': 1785,
 'common': 1923,
 'declare': 2217,
 'lol': 4190,
 'trust': 7065,
 'kitty': 3951,
 'shaved': 6078,
 'natural': 4717,
 'thanks': 6817,
 'ringtone': 5794,
 'order': 4997,
 'reference': 5653,
 'x49': 7657,
 'charged': 1741,
 'should': 6127,
 'arrive': 1084,
 'customer': 2135,
 'services': 6038,
 '09065989182': 219,
 'night': 4789,
 'ended': 2590,
 'another': 985,
 'special': 6374,
 'may': 4406,
 'smile': 6258,
 'sunny': 6612,
 'rays': 5586,
 'leaves': 4066,
 'worries': 7614,
 'blue': 1411,
 'bay': 1260,
 'lost': 4219,
 'pounds': 5360,
 'visit': 7320,
 'woot': 7599,
 'gonna': 3182,
 'celebrate': 1709,
 'stuffing': 6554,
 'ding': 2334,
 'break': 1494,
 'fassyole': 2782,
 'blacko': 1380,
 'londn': 4193,
 'news': 4776,
 'freefone': 2991,
 '08006344447': 57,
 '2000': 348,
 'gift': 3134,
 'speak': 6372,
 'operator': 4977,
 'mean': 4418,
 'confirmed': 1964,
 'oni': 4956,
 'freemsg': 2994,
 'ready': 5602,
 'horny': 3495,
 'town': 7015,
 'sex': 6050,
 'fun': 3045,
 'games': 3072,
 'netcollex': 4757,
 'ltd': 4256,
 '08700621170150p': 69,
 'per': 5163,
 'reply': 5719,
 'afternoon': 864,
 'ym': 7712,
 'tm': 6936,
 'smart': 6249,
 'move': 4610,
 'slave': 6222,
 'smiles': 6260,
 'drink': 2457,
 'coffee': 1885,
 'maximize': 4405,
 'send': 6016,
 'collect': 1898,
 '83600': 674,
 'cc': 1702,
 '08718720201': 134,
 '114': 270,
 '14': 290,
 'tcr': 6742,
 'w1': 7349,
 'awesome': 1179,
 'restocked': 5755,
 'definitely': 2230,
 'module': 4561,
 'humanities': 3543,
 'sem': 6011,
 'izzit': 3771,
 'modules': 4562,
 '1st': 336,
 'few': 2824,
 'people': 5161,
 'game': 3071,
 'mall': 4339,
 'iouri': 3726,
 'kaila': 3883,
 'thursday': 6899,
 'ft': 3030,
 'combination': 1909,
 'coming': 1917,
 'friday': 3005,
 'leave': 4065,
 'pongal': 5315,
 'place': 5243,
 'ans': 986,
 'bslvyl': 1542,
 'via': 7290,
 'fullonsms': 3043,
 'remember': 5688,
 'alex': 911,
 'about': 767,
 'pizza': 5241,
 'hdd': 3366,
 'casing': 1686,
 'looks': 4206,
 'wrong': 7641,
 'kappa': 3895,
 'numbers': 4868,
 'still': 6497,
 'him': 3428,
 'around': 1078,
 'baaaaaaaabe': 1194,
 'wake': 7375,
 'crave': 2064,
 'go': 3162,
 '86688': 691,
 'small': 6247,
 'dose': 2429,
 'tablet': 6689,
 'fever': 2823,
 'idea': 3582,
 'anyplaces': 1004,
 'doing': 2409,
 'lot': 4220,
 'pick': 5216,
 'engin': 2601,
 'saw': 5931,
 'both': 1452,
 'happy': 3334,
 'battery': 1257,
 'low': 4246,
 'congrats': 1968,
 '3g': 459,
 'videophones': 7299,
 'yours': 7729,
 '09063458130': 203,
 'videochat': 7298,
 'mates': 4388,
 'play': 5255,
 'java': 3794,
 'dload': 2381,
 'polyph': 5312,
 'noline': 4820,
 'rentl': 5708,
 'darlin': 2174,
 'college': 1902,
 'mt': 4632,
 'pete': 5189,
 'xx': 7668,
 'says': 5936,
 'money': 4574,
 'check': 1762,
 'appointment': 1034,
 'making': 4335,
 'mr': 4619,
 'sea': 5973,
 'view': 7303,
 'couple': 2041,
 'gays': 3093,
 'give': 3147,
 'bell': 1318,
 'finish': 2862,
 'funeral': 3049,
 'home': 3466,
 'tonight': 6980,
 'performed': 5167,
 'seems': 5996,
 'unnecessarily': 7186,
 'affectionate': 854,
 'activate': 812,
 'messages': 4467,
 'word': 7601,
 'terms': 6786,
 'conditions': 1959,
 '07781482378': 29,
 'choose': 1811,
 'future': 3057,
 'strong': 6536,
 'arms': 1074,
 'turn': 7089,
 'heater': 3385,
 'set': 6041,
 'degrees': 2233,
 'city': 1828,
 'summer': 6606,
 'shopping': 6117,
 'spree': 6424,
 '88039': 704,
 'skilgme': 6209,
 'tscs087147403231winawk': 7075,
 'age16': 871,
 '50perwksub': 545,
 'gr8': 3212,
 'leaving': 4067,
 'school': 5946,
 'plans': 5253,
 'jus': 3870,
 'came': 1631,
 'fr': 2976,
 'wif': 7524,
 'leh': 4076,
 'xin': 7663,
 'hostel': 3500,
 'lemme': 4078,
 'whenever': 7496,
 'todays': 6952,
 '800': 640,
 '09050001808': 162,
 'land': 4002,
 'line': 4126,
 'm95': 4291,
 'valid12hrs': 7258,
 'certainly': 1720,
 'puts': 5517,
 'things': 6856,
 'into': 3713,
 'perspective': 5185,
 'happens': 3329,
 'vodafone': 7331,
 'ending': 2591,
 '4882': 509,
 'selected': 6003,
 'receive': 5628,
 '350': 445,
 '09064019014': 212,
 'car': 1656,
 'gone': 3181,
 '4the': 528,
 'test': 6795,
 'uploaded': 7210,
 'mine': 4495,
 'facebook': 2744,
 'wnt': 7579,
 'bmw': 1416,
 'urgently': 7221,
 'vry': 7346,
 'hv': 3563,
 'shortage': 6121,
 'lacs': 3991,
 'source': 6354,
 'arng': 1075,
 'amt': 958,
 'romantic': 5817,
 '2006': 351,
 'fifa': 2833,
 'world': 7610,
 'cup': 2122,
 'held': 3393,
 '87239': 701,
 'service': 6037,
 'weekend': 7455,
 'hello': 3398,
 'hun': 3545,
 'ru': 5844,
 'here': 3409,
 'dates': 2183,
 'guy': 3282,
 'met': 4472,
 'walkabout': 7379,
 'far': 2778,
 'soon': 6330,
 'hows': 3520,
 'everyone': 2676,
 'else': 2572,
 'cozy': 2052,
 'nobody': 4809,
 'closed': 1859,
 'stand': 6449,
 'close': 1857,
 'tho': 6873,
 'catch': 1691,
 'absolutly': 773,
 'yunny': 7741,
 'walking': 7382,
 'citylink': 1829,
 'faster': 2784,
 'hungry': 3548,
 'lar': 4015,
 'dinner': 2336,
 'tv': 7094,
 'show': 6133,
 'start': 6460,
 'busy': 1579,
 'report': 5722,
 'height': 3392,
 'confidence': 1961,
 'aeronautics': 848,
 'professors': 5449,
 'wer': 7476,
 'calld': 1618,
 'askd': 1100,
 'sit': 6195,
 'aeroplane': 849,
 'aftr': 866,
 'sat': 5916,
 'dat': 2180,
 'plane': 5249,
 'ws': 7644,
 'made': 4309,
 'students': 6546,
 'dey': 2294,
 'hurried': 3554,
 'didnt': 2312,
 'wont': 7595,
 'datz': 2186,
 'tkts': 6933,
 'euro2004': 2659,
 'final': 2853,
 '09058099801': 184,
 'b4190604': 1188,
 ...}

In [20]:
Doc_Term_Matrix = pd.DataFrame(a, columns=cv.get_feature_names_out())

In [21]:
Doc_Term_Matrix

,00,000,000pes,008704050406,0125698789,02,0207,02072069400,02073162414,02085076972,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,Ã¨n,Ãº1,ã¨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
x_train.iloc[2]

'Urgent! call 09066612661 from landline. Your complementary 4* Tenerife Holiday or Â£10,000 cash await collection SAE T&Cs PO Box 3 WA14 2PX 150ppm 18+ Sender: Hol Offer'